## Trabajo Práctico: ETL con Python y Pandas

A partir del archivo `ventas.json`, realiza un proceso ETL en Python utilizando Pandas como herramienta principal en sus tres fases. Responde las preguntas propuestas en **celdas Markdown**.

### Fase 1: Extracción

1. Carga `ventas.json` en un DataFrame de Pandas.
    - Presenta el total de registros, los nombres de los campos y los tipos de datos iniciales detectados por Pandas.

2. Realiza un perfil inicial del conjunto de datos utilizando `isna()`, `describe()` y `nunique()`. El perfil debe permitir observar:
    - la cantidad de valores ausentes por campo;
    - un resumen descriptivo de los datos;
    - la cantidad de valores únicos por campo.

A partir de los resultados obtenidos, responde en una celda Markdown: ¿qué problemas podríamos encontrar en el conjunto de datos y qué campos requerirían transformaciones o validaciones?

## Actividad 1 :

In [1]:
import pandas as pd

ventas = pd.read_json("ventas.json")
ventas.head()

,id,producto,ciudad,precio,cantidad,estado,fecha,comentario_interno
0,1,Notebook,Formosa,25000,2.0,pendiente,2026-08-05,NaN
1,2,Notebook,Resistencia,15000,5.0,enviado,2026-08-02,NaN
2,3,Notebook,Formosa,25000,2.0,entregado,2026-08-20,NaN
3,4,Notebook,Resistencia,25000,5.0,enviado,2026-08-08,NaN
4,5,Monitor,Resistencia,35000,1.0,pendiente,2026-08-23,NaN

In [10]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        2000 non-null   int64
 1   producto  2000 non-null   str
 2   ciudad    2000 non-null   str
 3   precio    1998 non-null   object
 4   cantidad  1999 non-null   float64
 5   estado    1999 non-null   str
 6   fecha     1989 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), object(1), str(3)
memory usage: 109.5+ KB

## Actividad 2:

In [2]:
valores_ausentes= ventas.isna().sum()
valores_ausentes

id                       0
producto                 0
ciudad                   0
precio                   2
cantidad                 1
estado                   1
fecha                    1
comentario_interno    2002
dtype: int64

In [3]:
ventas.describe()

                id     cantidad
count  2003.000000  2002.000000
mean   1000.592611     3.026474
std     577.402809     1.488184
min       1.000000   -10.000000
25%     500.500000     2.000000
50%    1001.000000     3.000000
75%    1500.500000     4.000000
max    2000.000000     5.000000

In [165]:
ventas.nunique(),ventas.count()

(id          1978
 producto       5
 ciudad         5
 precio         5
 cantidad       5
 estado         3
 fecha         27
 dtype: int64,
 id          1978
 producto    1978
 ciudad      1978
 precio      1978
 cantidad    1978
 estado      1978
 fecha       1970
 dtype: int64)

en conjuntos de datos se puede ver que hay valores nulos que contiene la columna comentario_interno, mientras que el resumen que hago en ventas se que en una cantidad muestran valores negativos como por ejemplo -10.000.000 lo cual seria incorrecta en precio de ventas

### Fase 2: Transformación

Realiza las siguientes transformaciones y validaciones sobre el DataFrame utilizando Pandas.

3. Algunas ciudades aparecen escritas con diferencias de mayúsculas, minúsculas o espacios adicionales. Normaliza sus valores para que cada ciudad tenga una única representación.

4. Convierte los precios numéricos almacenados como texto (por ejemplo, `"25000"`) a un tipo numérico adecuado dentro del DataFrame.
    - Identifica como inválidas las ventas cuyos precios no puedan convertirse a un valor numérico.

5. ¿Qué reglas de negocio puedes establecer para los campos `cantidad` y `precio`?
    - Define y valida esas reglas para identificar las ventas inválidas.
    - **Pista**: Revisa el tipo de dato y el **rango** de los campos, con `.max()` y `.min()` de Pandas.

6. Valida mediante Pandas que el campo `estado` contenga uno de los siguientes valores:
    - `pendiente`
    - `enviado`
    - `entregado`

7. Valida que las fechas tengan el formato `YYYY-MM-DD` e identifica las ventas que no cumplan esta condición.

8. ¿Todos los campos son necesarios? Utiliza Pandas para excluir los campos innecesarios del conjunto de datos final.

9. Como última transformación, verifica si existen registros completamente duplicados. Informa cuántos encontraste y elimina las copias adicionales antes de construir el conjunto de datos final.

## Actividad 3:

In [71]:
ventas_copia = ventas.copy()
ventas_copia["ciudad"]= ventas_copia["ciudad"].str.upper().str.strip()

ventas_copia.head()

   id  producto       ciudad   precio  cantidad     estado      fecha
0   1  Notebook      FORMOSA  25000.0       2.0  pendiente 2026-08-05
1   2  Notebook  RESISTENCIA  15000.0       5.0    enviado 2026-08-02
2   3  Notebook      FORMOSA  25000.0       2.0  entregado 2026-08-20
3   4  Notebook  RESISTENCIA  25000.0       5.0    enviado 2026-08-08
4   5   Monitor  RESISTENCIA  35000.0       1.0  pendiente 2026-08-23

## Actividad 4:

In [70]:
ventas_copia["precio"] = pd.to_numeric(ventas_copia["precio"],errors="coerce") 
ventas_copia

        id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      Formosa   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  Resistencia   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      Formosa   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  Resistencia   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  Resistencia   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  Resistencia  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      Formosa   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     Clorinda   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  Resistencia   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      formosa   35000.0       2.0  pendiente 2026-08-08

[1984 rows x 7 columns]

## Actividad 5:

In [17]:
ventas["cantidad"].min()

np.float64(-10.0)

In [69]:


ventas_copia = ventas_copia.loc[ventas["cantidad"] > 0]
ventas_copia

        id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      Formosa   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  Resistencia   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      Formosa   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  Resistencia   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  Resistencia   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  Resistencia  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      Formosa   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     Clorinda   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  Resistencia   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      formosa   35000.0       2.0  pendiente 2026-08-08

[1984 rows x 7 columns]

In [68]:
ventas_copia

        id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      Formosa   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  Resistencia   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      Formosa   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  Resistencia   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  Resistencia   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  Resistencia  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      Formosa   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     Clorinda   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  Resistencia   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      formosa   35000.0       2.0  pendiente 2026-08-08

[1991 rows x 7 columns]

In [55]:
ventas_copia.loc[ventas["cantidad"] < 0]

        id     producto       ciudad    precio  cantidad     estado      fecha
286    287     Notebook      FORMOSA  850000.0      -2.0  entregado 2026-08-26
613    614        Mouse      FORMOSA   15000.0      -3.0  pendiente        NaT
1522  1523  Auriculares  RESISTENCIA  850000.0      -1.0  pendiente 2026-08-16
1532  1533     Notebook     CLORINDA   25000.0      -5.0  pendiente 2026-08-06
1943  1944        Mouse      FORMOSA   15000.0     -10.0  pendiente 2026-08-26

In [67]:
ventas_copia["cantidad"].max()

np.float64(5.0)

In [58]:
ventas_copia["cantidad"].min()

np.float64(-10.0)

In [63]:
ventas_copia["precio"] = pd.to_numeric(ventas_copia["precio"], errors="coerce")
ventas_copia["precio"].min()

np.float64(15000.0)

In [72]:
ventas_copia = ventas_copia.loc[ventas_copia["precio"] > 0]
ventas_copia

        id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      FORMOSA   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  RESISTENCIA   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      FORMOSA   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  RESISTENCIA   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  RESISTENCIA   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  RESISTENCIA  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      FORMOSA   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     CLORINDA   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  RESISTENCIA   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      FORMOSA   35000.0       2.0  pendiente 2026-08-08

[1991 rows x 7 columns]

In [74]:
ventas_copia = ventas_copia.loc[ventas_copia["cantidad"] > 0]
ventas_copia

        id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      FORMOSA   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  RESISTENCIA   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      FORMOSA   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  RESISTENCIA   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  RESISTENCIA   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  RESISTENCIA  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      FORMOSA   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     CLORINDA   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  RESISTENCIA   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      FORMOSA   35000.0       2.0  pendiente 2026-08-08

[1984 rows x 7 columns]

In [77]:
ventas_copia.loc[ventas["precio"] < 0]

Empty DataFrame
Columns: [id, producto, ciudad, precio, cantidad, estado, fecha]
Index: []

In [78]:
ventas_copia["precio"].min()

np.float64(15000.0)

## Actividad 6:

In [79]:
# Ver todos los valores únicos de la columna 'estado'
ventas_copia["estado"].unique()

<StringArray>
[  'pendiente',     'enviado',   'entregado',            '', 'desconocido',
           nan,  'pendiente ',   'cancelado',   'Entregado']
Length: 9, dtype: str

In [80]:
estados_validos = ["pendiente","enviado","entregado"]

ventas_copia = ventas_copia.loc[ventas_copia["estado"].isin(estados_validos)]
ventas_copia["estado"].unique()

<StringArray>
['pendiente', 'enviado', 'entregado']
Length: 3, dtype: str

## Actividad 7

In [81]:
ventas_copia["fecha"].unique()

<DatetimeArray>
['2026-08-05 00:00:00', '2026-08-02 00:00:00', '2026-08-20 00:00:00',
 '2026-08-08 00:00:00', '2026-08-23 00:00:00', '2026-08-25 00:00:00',
 '2026-08-12 00:00:00', '2026-08-15 00:00:00', '2026-08-10 00:00:00',
 '2026-08-03 00:00:00', '2026-08-04 00:00:00', '2026-08-21 00:00:00',
 '2026-08-13 00:00:00', '2026-08-07 00:00:00', '2026-08-24 00:00:00',
 '2026-08-19 00:00:00', '2026-08-16 00:00:00', '2026-08-06 00:00:00',
 '2026-08-22 00:00:00',                 'NaT', '2026-08-18 00:00:00',
 '2026-08-26 00:00:00', '2026-08-11 00:00:00', '2026-08-14 00:00:00',
 '2026-08-17 00:00:00', '2026-08-01 00:00:00', '2026-08-27 00:00:00',
 '2026-08-09 00:00:00']
Length: 28, dtype: datetime64[us]

In [82]:
fechas_faltantes = ventas_copia.loc[ventas_copia["fecha"].isna()]
fechas_faltantes

        id     producto       ciudad    precio  cantidad     estado fecha
27      28        Mouse  RESISTENCIA  850000.0       1.0  entregado   NaT
122    123  Auriculares     CLORINDA   35000.0       1.0  entregado   NaT
227    228     Notebook     CLORINDA  120000.0       3.0  entregado   NaT
319    320  Auriculares      FORMOSA   25000.0       4.0  entregado   NaT
587    588      Teclado      FORMOSA  120000.0       5.0    enviado   NaT
1315  1316        Mouse  RESISTENCIA   15000.0       3.0    enviado   NaT
1423  1424        Mouse      FORMOSA  850000.0       2.0    enviado   NaT
1804  1805      Monitor      FORMOSA  850000.0       4.0    enviado   NaT

In [83]:
ventas_copia["fecha"] = pd.to_datetime(ventas_copia["fecha"], errors="coerce")
ventas_copia

        id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      FORMOSA   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  RESISTENCIA   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      FORMOSA   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  RESISTENCIA   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  RESISTENCIA   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  RESISTENCIA  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      FORMOSA   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     CLORINDA   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  RESISTENCIA   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      FORMOSA   35000.0       2.0  pendiente 2026-08-08

[1978 rows x 7 columns]

In [84]:
ventas_copia["fecha"].unique()

<DatetimeArray>
['2026-08-05 00:00:00', '2026-08-02 00:00:00', '2026-08-20 00:00:00',
 '2026-08-08 00:00:00', '2026-08-23 00:00:00', '2026-08-25 00:00:00',
 '2026-08-12 00:00:00', '2026-08-15 00:00:00', '2026-08-10 00:00:00',
 '2026-08-03 00:00:00', '2026-08-04 00:00:00', '2026-08-21 00:00:00',
 '2026-08-13 00:00:00', '2026-08-07 00:00:00', '2026-08-24 00:00:00',
 '2026-08-19 00:00:00', '2026-08-16 00:00:00', '2026-08-06 00:00:00',
 '2026-08-22 00:00:00',                 'NaT', '2026-08-18 00:00:00',
 '2026-08-26 00:00:00', '2026-08-11 00:00:00', '2026-08-14 00:00:00',
 '2026-08-17 00:00:00', '2026-08-01 00:00:00', '2026-08-27 00:00:00',
 '2026-08-09 00:00:00']
Length: 28, dtype: datetime64[us]

## Actividad 8 :

In [85]:
ventas_copia.columns

Index(['id', 'producto', 'ciudad', 'precio', 'cantidad', 'estado', 'fecha'], dtype='str')

In [ ]:
ventas_copia = ventas_copia.drop(columns=["comentario_interno"])
ventas_copia

In [86]:
ventas_copia.columns

Index(['id', 'producto', 'ciudad', 'precio', 'cantidad', 'estado', 'fecha'], dtype='str')

## Actividad 9:

In [87]:
ventas_copia.duplicated().sum()

np.int64(0)

In [88]:
ventas_copia = ventas_copia.drop_duplicates()
ventas_copia

        id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      FORMOSA   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  RESISTENCIA   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      FORMOSA   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  RESISTENCIA   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  RESISTENCIA   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  RESISTENCIA  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      FORMOSA   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     CLORINDA   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  RESISTENCIA   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      FORMOSA   35000.0       2.0  pendiente 2026-08-08

[1978 rows x 7 columns]

## Actividad 10:

In [89]:
ventas_validas = ventas_copia.copy()
ventas_validas.head()

   id  producto       ciudad   precio  cantidad     estado      fecha
0   1  Notebook      FORMOSA  25000.0       2.0  pendiente 2026-08-05
1   2  Notebook  RESISTENCIA  15000.0       5.0    enviado 2026-08-02
2   3  Notebook      FORMOSA  25000.0       2.0  entregado 2026-08-20
3   4  Notebook  RESISTENCIA  25000.0       5.0    enviado 2026-08-08
4   5   Monitor  RESISTENCIA  35000.0       1.0  pendiente 2026-08-23

## Fase 3: Carga

A partir de los resultados obtenidos con Pandas:

10. Construye el DataFrame final de ventas **válidas y transformadas**. Toda venta que incumpla al menos una validación debe quedar excluida de este DataFrame.

11. Antes de guardar los resultados, presenta un resumen de calidad que incluya:

- cantidad total de ventas procesadas;
- cantidad de registros duplicados eliminados;
- cantidad de ventas válidas;
- cantidad de ventas rechazadas.

12. Guarda el DataFrame de ventas válidas en un nuevo archivo llamado `ventas_limpias.json`.

## Actividad 11:

In [90]:
total_procesadas = len(ventas)         
duplicados_eliminados = 3               
ventas_validas_total = len(ventas_validas) #
ventas_rechazadas = total_procesadas - ventas_validas_total

In [91]:
total_procesadas
duplicados_eliminados
ventas_validas_total
ventas_rechazadas

13

In [93]:
print(f"en total de ventas procesadas: {total_procesadas}")

en total de ventas procesadas: 1991

In [95]:
print(f"los duplicdos son entre : {duplicados_eliminados}")

los duplicdos son entre : 3

In [97]:
print((f"ventas validas: {ventas_validas}"))

ventas validas:         id  producto       ciudad    precio  cantidad     estado      fecha
0        1  Notebook      FORMOSA   25000.0       2.0  pendiente 2026-08-05
1        2  Notebook  RESISTENCIA   15000.0       5.0    enviado 2026-08-02
2        3  Notebook      FORMOSA   25000.0       2.0  entregado 2026-08-20
3        4  Notebook  RESISTENCIA   25000.0       5.0    enviado 2026-08-08
4        5   Monitor  RESISTENCIA   35000.0       1.0  pendiente 2026-08-23
...    ...       ...          ...       ...       ...        ...        ...
1995  1996     Mouse  RESISTENCIA  120000.0       2.0  pendiente 2026-08-27
1996  1997     Mouse      FORMOSA   25000.0       1.0  entregado 2026-08-23
1997  1998     Mouse     CLORINDA   15000.0       4.0    enviado 2026-08-02
1998  1999  Notebook  RESISTENCIA   15000.0       4.0  entregado 2026-08-06
1999  2000  Notebook      FORMOSA   35000.0       2.0  pendiente 2026-08-08

[1978 rows x 7 columns]

In [98]:
print(f"las ventas rechazadas son : {ventas_rechazadas}")

las ventas rechazadas son : 13

## Actividad 12

In [99]:
ventas_validas.to_json("ventas_limpias", orient="records", indent=4)

C:\Users\IPF-2026\AppData\Local\Temp\ipykernel_3244\4045601228.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  ventas_validas.to_json("ventas_limpias", orient="records", indent=4)

## Desafío opcional: registro de *dead letters*

Además del proceso ETL principal, puedes conservar los errores detectados en un DataFrame separado. Cada fila debe representar un único error e incluir los datos originales completos de la venta, el campo inválido, su valor original y la razón del error. Si una venta presenta más de un error, debe generar una fila por cada validación incumplida.

Por ejemplo, una fila del DataFrame de errores podría tener la siguiente estructura:

```json
{
    "id": 101,
    "producto": "Mouse",
    "ciudad": "Formosa",
    "precio": -15000,
    "cantidad": 2,
    "estado": "pendiente",
    "fecha": "2026-08-12",
    "comentario_interno": "dato que no necesitamos",
    "campo_invalido": "precio",
    "valor_original": -15000,
    "razon": "el precio debe ser mayor que cero"
}
```

Amplía el resumen de calidad para incluir:

- cantidad total de errores;
- cantidad de errores por campo y por razón.

Explica en una celda Markdown por qué la cantidad de ventas rechazadas puede ser diferente de la cantidad total de errores. Finalmente, guarda el DataFrame de errores en un archivo llamado `errors.json`.

**Dato curioso:** en los procesos de datos, los registros que no pueden continuar por errores de validación suelen denominarse *dead letters*. Separarlos permite analizarlos y corregirlos sin detener el procesamiento de los registros válidos.